version: '3.7'
services:
  nginx: 
    image: nginx
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    build: 
      context: .
      dockerfile: ./nginx/nginx/Dockerfile
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro      
      - ./nginx/cert:/cert
      #- ./nginx:/etc/nginx

  nginx1: 
    image: nginx:1.21
    container_name: nginx1
    ports:
    - "81:80"
    volumes:
      - ./nginx/html1:/usr/share/nginx/html:ro   
  
  nginx2: 
    image: nginx:1.21
    container_name: nginx2
    ports:
    - "82:80"
    volumes:
      - ./nginx/html2:/usr/share/nginx/html:ro 

  nginx3: 
    image: nginx:1.21
    container_name: nginx3
    ports:
    - "83:80"
    volumes:
      - ./nginx/html3:/usr/share/nginx/html:ro  
    