version: '3.7'
services:
  nginx: 
    image: nginx
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    build: 
      context: .
      dockerfile: ./nginx/nginx/Dockerfile
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro    
      - ./nginx/cert:/cert
      
  server1: 
    image: nginx:1.21
    container_name: server1
    ports:
    - "81:80"
    volumes:
      - ./nginx/html1:/usr/share/nginx/html:ro    
  
  sever2: 
    image: nginx:1.21
    container_name: server2
    ports:
    - "82:80"
    volumes:
      - ./nginx/html2:/usr/share/nginx/html:ro   

  serverbkp: 
    image: nginx:1.21
    container_name: server3
    ports:
    - "83:80"
    volumes:
      - ./nginx/html3:/usr/share/nginx/html:ro    
    